version: "3"
services:
  ipfs:
    restart: always
    image: ipfs/go-ipfs
    environment:
      MYVAR: test
    volumes:
      - /home/guruvan/ipfs_upload:/data/ipfs
      - /home/guruvan/maza_network_web/mazacoin.org/_site:/data/mazacoin_org
      - /home/guruvan/maza_network:/data/maza_nodes
      - /home/guruvan/maza_network_web/:/data/maza_network_web
    ports:
      - 4001:4001
      - 8000:8080
      - 8001:5001
    command:
      - "--enable-pubsub-experiment"

  
